export const HOTELS = [
  "Aloft Bengaluru Outer Ring Road",
  "Aloft Bengaluru Whitefield",
  "Aloft New Delhi Aerocity",
  "Aravali Marriott Resort & Spa, Delhi NCR",
  "Coorg Marriott Resort & Spa",
  "Courtyard Agra",
  "Courtyard Ahmedabad Sindhu Bhavan Road",
  "Courtyard Ahmedabad",
  "Courtyard Amritsar",
  "Courtyard Aravali Resort",
  "Courtyard Bengaluru Hebbal",
  "Courtyard Bengaluru Outer Ring Road",
  "Courtyard Bhopal",
  "Courtyard Bilaspur",
  "Courtyard Chennai",
  "Courtyard Gorakhpur",
  "Courtyard Gurugram Downtown",
  "Courtyard Hyderabad",
  "Courtyard Kochi Airport",
  "Courtyard Mahabaleshwar",
  "Courtyard Mumbai International Airport",
  "Courtyard Nashik",
  "Courtyard Navi Mumbai",
  "Courtyard Pune Chakan",
  "Courtyard Pune Hinjewadi",
  "Courtyard Raipur",
  "Courtyard Shillong",
  "Courtyard Siliguri",
  "Courtyard Surat",
  "Courtyard Tiruchirappalli",
  "Courtyard Vadodara",
  "Courtyard by Marriott Aravali Resort",
  "Courtyard by Marriott Bengaluru Hebbal",
  "Courtyard by Marriott Bengaluru Outer Ring Road",
  "Courtyard by Marriott Bhopal",
  "Courtyard by Marriott Bilaspur",
  "Courtyard by Marriott Chennai",
  "Courtyard by Marriott Goa Colva",
  "Courtyard by Marriott Hyderabad",
  "Courtyard by Marriott Madurai",
  "Courtyard by Marriott Ranchi",
  "Courtyard by Marriott Surat",
  "Courtyard by Marriott Vadodara",
  "Fairfield by Marriott Agra",
  "Fairfield by Marriott Ahmedabad",
  "Fairfield by Marriott Amritsar",
  "Fairfield by Marriott Belagavi",
  "Fairfield by Marriott Bengaluru Outer Ring Road",
  "Fairfield by Marriott Bengaluru Rajajinagar",
  "Fairfield by Marriott Bengaluru Whitefield",
  "Fairfield by Marriott Chennai Mahindra World City",
  "Fairfield by Marriott Chennai OMR",
  "Fairfield by Marriott Coimbatore",
  "Fairfield by Marriott Dehradun",
  "Fairfield by Marriott Goa Anjuna",
  "Fairfield by Marriott Goa Benaulim",
  "Fairfield by Marriott Goa Calangute",
  "Fairfield by Marriott Hyderabad Gachibowli",
  "Fairfield by Marriott Indore",
  "Fairfield by Marriott Jaipur",
  "Fairfield by Marriott Jodhpur",
  "Fairfield by Marriott Kolkata",
  "Fairfield by Marriott Lucknow",
  "Fairfield by Marriott Mumbai Andheri West",
  "Fairfield by Marriott Mumbai International Airport",
  "Fairfield by Marriott Pune Kharadi",
  "Fairfield by Marriott Sriperumbudur",
  "Fairfield by Marriott Vadodara",
  "Fairfield by Marriott Visakhapatnam",
  "Four Points by Sheraton Ahmedabad",
  "Four Points by Sheraton Amritsar, Mall Road",
  "Four Points by Sheraton Bengaluru, Whitefield",
  "Four Points by Sheraton Chennai OMR",
  "Four Points by Sheraton Chennai, Velachery",
  "Four Points by Sheraton Hotel & Serviced Apartments, Pune",
  "Four Points by Sheraton Jaipur, City Square",
  "Four Points by Sheraton Kochi Infopark",
  "Four Points by Sheraton Mahabalipuram Resort & Convention Center",
  "Four Points by Sheraton Nashik",
  "Four Points by Sheraton Navi Mumbai, Vashi",
  "Four Points by Sheraton New Delhi, Airport Highway",
  "Four Points by Sheraton Sonmarg Resort",
  "Four Points by Sheraton Srinagar",
  "Four Points by Sheraton Vadodara",
  "Four Points by Sheraton Visakhapatnam",
  "Goa Marriott Resort & Spa",
  "Hyderabad Marriott Hotel & Convention Centre",
  "Indore Marriott Hotel",
  "JW Marriott Bengaluru Prestige Golfshire Resort & Spa",
  "JW Marriott Goa",
  "JW Marriott Hotel Bengaluru",
  "JW Marriott Hotel Chandigarh",
  "JW Marriott Hotel Kolkata",
  "JW Marriott Hotel New Delhi Aerocity",
  "JW Marriott Hotel Pune",
  "JW Marriott Mumbai Juhu",
  "JW Marriott Mumbai Sahar",
  "JW Marriott Mussoorie Walnut Grove Resort & Spa",
  "Jaipur Marriott Hotel",
  "Jaisalmer Marriott Resort & Spa",
  "Jim Corbett Marriott Resort & Spa",
  "Katra Marriott Resort & Spa",
  "Kochi Marriott Hotel",
  "Lakeside Chalet, Mumbai - Marriott Executive Apartments",
  "Le Meridien Ahmedabad",
  "Le Meridien Amritsar",
  "Le Meridien Coimbatore",
  "Le Meridien Dehradun Resort & Spa",
  "Le Meridien Goa, Calangute",
  "Le Meridien Gurgaon, Delhi NCR",
  "Le Meridien Hyderabad",
  "Le Meridien Jaipur Resort & Spa",
  "Le Meridien Kochi",
  "Le Meridien Mahabaleshwar Resort & Spa",
  "Le Meridien Nagpur",
  "Le Meridien Navi Mumbai",
  "Le Meridien New Delhi",
  "Le Royal Meridien Chennai",
  "Marriott Executive Apartments Bengaluru UB City",
  "Marriott Executive Apartments Hyderabad",
  "Marriott Executive Apartments Mall Road Amritsar",
  "Marriott Executive Apartments Navi Mumbai",
  "Marriott Suites Pune",
  "Moxy Bengaluru Airport Prestige Tech Cloud",
  "Moxy Mumbai Andheri West",
  "Mulberry Shades Bengaluru Nandi Hills, a Tribute Portfolio Resort",
  "Navi Mumbai Marriott Hotel",
  "Port Muziris, a Tribute Portfolio Hotel, Kochi",
  "Renaissance Ahmedabad Hotel",
  "Renaissance Bengaluru Race Course Hotel",
  "Renaissance Goa Hotel",
  "Renaissance Lucknow Hotel",
  "Sheraton Grand Bangalore Hotel at Brigade Gateway",
  "Sheraton Grand Bengaluru Whitefield Hotel & Convention Center",
  "Sheraton Grand Chennai Resort & Spa",
  "Sheraton Grand Palace Indore",
  "Sheraton Grand Pune Bund Garden Hotel",
  "Sheraton Hyderabad Hotel",
  "Sheraton New Delhi Hotel",
  "Surat Marriott Hotel",
  "THE ARTISTE KOCHI, A TRIBUTE PORTFOLIO HOTEL",
  "The Ritz-Carlton, Bangalore",
  "The Ritz-Carlton, Pune",
  "The St. Regis Goa Resort",
  "The St. Regis Mumbai",
  "The Westin Chennai Velachery",
  "The Westin Goa",
  "The Westin Gurgaon, New Delhi",
  "The Westin Hyderabad Hitec City",
  "The Westin Hyderabad Mindspace",
  "The Westin Kolkata Rajarhat",
  "The Westin Mumbai Garden City",
  "The Westin Mumbai Powai Lake",
  "The Westin Pune Koregaon Park",
  "The Westin Pushkar Resort & Spa",
  "The Westin Resort & Spa, Himalayas",
  "The Westin Sohna Resort & Spa",
  "Trinity Whitefield Bengaluru",
  "Udaipur Marriott Hotel",
  "W Goa",
  "Other",
];
