// Per-property hotel logos, generated from a real logo image set supplied
// for (almost) every hotel in lib/hotels.js — see git history for the source
// batch. Falls back to the generic per-brand mark in lib/hotelBrands.js for
// the handful of properties without one yet (see the missing list there).
export const HOTEL_PROPERTY_LOGOS = {
  "Aloft Bengaluru Outer Ring Road": "/hotel-logos/property/aloft-bengaluru-outer-ring-road.png",
  "Aloft Bengaluru Whitefield": "/hotel-logos/property/aloft-bengaluru-whitefield.png",
  "Aloft New Delhi Aerocity": "/hotel-logos/property/aloft-new-delhi-aerocity.png",
  "Aravali Marriott Resort & Spa, Delhi NCR": "/hotel-logos/property/aravali-marriott-resort-and-spa-delhi-ncr.png",
  "Coorg Marriott Resort & Spa": "/hotel-logos/property/coorg-marriott-resort-and-spa.png",
  "Courtyard Agra": "/hotel-logos/property/courtyard-agra.png",
  "Courtyard Ahmedabad Sindhu Bhavan Road": "/hotel-logos/property/courtyard-ahmedabad-sindhu-bhavan-road.png",
  "Courtyard Ahmedabad": "/hotel-logos/property/courtyard-ahmedabad.png",
  "Courtyard Amritsar": "/hotel-logos/property/courtyard-amritsar.png",
  "Courtyard Gorakhpur": "/hotel-logos/property/courtyard-gorakhpur.png",
  "Courtyard Gurugram Downtown": "/hotel-logos/property/courtyard-gurugram-downtown.png",
  "Courtyard Kochi Airport": "/hotel-logos/property/courtyard-kochi-airport.png",
  "Courtyard Mahabaleshwar": "/hotel-logos/property/courtyard-mahabaleshwar.png",
  "Courtyard Mumbai International Airport": "/hotel-logos/property/courtyard-mumbai-international-airport.png",
  "Courtyard Nashik": "/hotel-logos/property/courtyard-nashik.png",
  "Courtyard Navi Mumbai": "/hotel-logos/property/courtyard-navi-mumbai.png",
  "Courtyard Pune Chakan": "/hotel-logos/property/courtyard-pune-chakan.png",
  "Courtyard Pune Hinjewadi": "/hotel-logos/property/courtyard-pune-hinjewadi.png",
  "Courtyard Raipur": "/hotel-logos/property/courtyard-raipur.png",
  "Courtyard Shillong": "/hotel-logos/property/courtyard-shillong.png",
  "Courtyard Siliguri": "/hotel-logos/property/courtyard-siliguri.png",
  "Courtyard Tiruchirappalli": "/hotel-logos/property/courtyard-tiruchirappalli.png",
  "Courtyard by Marriott Aravali Resort": "/hotel-logos/property/courtyard-by-marriott-aravali-resort.png",
  "Courtyard by Marriott Bengaluru Hebbal": "/hotel-logos/property/courtyard-by-marriott-bengaluru-hebbal.png",
  "Courtyard by Marriott Bengaluru Outer Ring Road": "/hotel-logos/property/courtyard-by-marriott-bengaluru-outer-ring-road.png",
  "Courtyard by Marriott Bhopal": "/hotel-logos/property/courtyard-by-marriott-bhopal.png",
  "Courtyard by Marriott Bilaspur": "/hotel-logos/property/courtyard-by-marriott-bilaspur.png",
  "Courtyard by Marriott Chennai": "/hotel-logos/property/courtyard-by-marriott-chennai.png",
  "Courtyard by Marriott Goa Colva": "/hotel-logos/property/courtyard-by-marriott-goa-colva.png",
  "Courtyard by Marriott Hyderabad": "/hotel-logos/property/courtyard-by-marriott-hyderabad.png",
  "Courtyard by Marriott Madurai": "/hotel-logos/property/courtyard-by-marriott-madurai.png",
  "Courtyard by Marriott Ranchi": "/hotel-logos/property/courtyard-by-marriott-ranchi.png",
  "Courtyard by Marriott Surat": "/hotel-logos/property/courtyard-by-marriott-surat.png",
  "Courtyard by Marriott Vadodara": "/hotel-logos/property/courtyard-by-marriott-vadodara.png",
  "Fairfield by Marriott Agra": "/hotel-logos/property/fairfield-by-marriott-agra.png",
  "Fairfield by Marriott Ahmedabad": "/hotel-logos/property/fairfield-by-marriott-ahmedabad.png",
  "Fairfield by Marriott Amritsar": "/hotel-logos/property/fairfield-by-marriott-amritsar.png",
  "Fairfield by Marriott Belagavi": "/hotel-logos/property/fairfield-by-marriott-belagavi.png",
  "Fairfield by Marriott Bengaluru Outer Ring Road": "/hotel-logos/property/fairfield-by-marriott-bengaluru-outer-ring-road.png",
  "Fairfield by Marriott Bengaluru Rajajinagar": "/hotel-logos/property/fairfield-by-marriott-bengaluru-rajajinagar.png",
  "Fairfield by Marriott Bengaluru Whitefield": "/hotel-logos/property/fairfield-by-marriott-bengaluru-whitefield.png",
  "Fairfield by Marriott Chennai Mahindra World City": "/hotel-logos/property/fairfield-by-marriott-chennai-mahindra-world-city.png",
  "Fairfield by Marriott Chennai OMR": "/hotel-logos/property/fairfield-by-marriott-chennai-omr.png",
  "Fairfield by Marriott Coimbatore": "/hotel-logos/property/fairfield-by-marriott-coimbatore.png",
  "Fairfield by Marriott Dehradun": "/hotel-logos/property/fairfield-by-marriott-dehradun.png",
  "Fairfield by Marriott Goa Anjuna": "/hotel-logos/property/fairfield-by-marriott-goa-anjuna.png",
  "Fairfield by Marriott Goa Benaulim": "/hotel-logos/property/fairfield-by-marriott-goa-benaulim.png",
  "Fairfield by Marriott Goa Calangute": "/hotel-logos/property/fairfield-by-marriott-goa-calangute.png",
  "Fairfield by Marriott Hyderabad Gachibowli": "/hotel-logos/property/fairfield-by-marriott-hyderabad-gachibowli.png",
  "Fairfield by Marriott Indore": "/hotel-logos/property/fairfield-by-marriott-indore.png",
  "Fairfield by Marriott Jaipur": "/hotel-logos/property/fairfield-by-marriott-jaipur.png",
  "Fairfield by Marriott Jodhpur": "/hotel-logos/property/fairfield-by-marriott-jodhpur.png",
  "Fairfield by Marriott Kolkata": "/hotel-logos/property/fairfield-by-marriott-kolkata.png",
  "Fairfield by Marriott Lucknow": "/hotel-logos/property/fairfield-by-marriott-lucknow.png",
  "Fairfield by Marriott Mumbai Andheri West": "/hotel-logos/property/fairfield-by-marriott-mumbai-andheri-west.png",
  "Fairfield by Marriott Mumbai International Airport": "/hotel-logos/property/fairfield-by-marriott-mumbai-international-airport.png",
  "Fairfield by Marriott Sriperumbudur": "/hotel-logos/property/fairfield-by-marriott-sriperumbudur.png",
  "Fairfield by Marriott Vadodara": "/hotel-logos/property/fairfield-by-marriott-vadodara.png",
  "Fairfield by Marriott Visakhapatnam": "/hotel-logos/property/fairfield-by-marriott-visakhapatnam.png",
  "Four Points by Sheraton Ahmedabad": "/hotel-logos/property/four-points-by-sheraton-ahmedabad.png",
  "Four Points by Sheraton Amritsar, Mall Road": "/hotel-logos/property/four-points-by-sheraton-amritsar-mall-road.png",
  "Four Points by Sheraton Bengaluru, Whitefield": "/hotel-logos/property/four-points-by-sheraton-bengaluru-whitefield.png",
  "Four Points by Sheraton Chennai OMR": "/hotel-logos/property/four-points-by-sheraton-chennai-omr.png",
  "Four Points by Sheraton Chennai, Velachery": "/hotel-logos/property/four-points-by-sheraton-chennai-velachery.png",
  "Four Points by Sheraton Hotel & Serviced Apartments, Pune": "/hotel-logos/property/four-points-by-sheraton-hotel-and-serviced-apartments-pune.png",
  "Four Points by Sheraton Jaipur, City Square": "/hotel-logos/property/four-points-by-sheraton-jaipur-city-square.png",
  "Four Points by Sheraton Kochi Infopark": "/hotel-logos/property/four-points-by-sheraton-kochi-infopark.png",
  "Four Points by Sheraton Mahabalipuram Resort & Convention Center": "/hotel-logos/property/four-points-by-sheraton-mahabalipuram-resort-and-convention-center.png",
  "Four Points by Sheraton Nashik": "/hotel-logos/property/four-points-by-sheraton-nashik.png",
  "Four Points by Sheraton Navi Mumbai, Vashi": "/hotel-logos/property/four-points-by-sheraton-navi-mumbai-vashi.png",
  "Four Points by Sheraton New Delhi, Airport Highway": "/hotel-logos/property/four-points-by-sheraton-new-delhi-airport-highway.png",
  "Four Points by Sheraton Sonmarg Resort": "/hotel-logos/property/four-points-by-sheraton-sonmarg-resort.png",
  "Four Points by Sheraton Srinagar": "/hotel-logos/property/four-points-by-sheraton-srinagar.png",
  "Four Points by Sheraton Vadodara": "/hotel-logos/property/four-points-by-sheraton-vadodara.png",
  "Four Points by Sheraton Visakhapatnam": "/hotel-logos/property/four-points-by-sheraton-visakhapatnam.png",
  "Goa Marriott Resort & Spa": "/hotel-logos/property/goa-marriott-resort-and-spa.png",
  "Hyderabad Marriott Hotel & Convention Centre": "/hotel-logos/property/hyderabad-marriott-hotel-and-convention-centre.png",
  "Indore Marriott Hotel": "/hotel-logos/property/indore-marriott-hotel.png",
  "JW Marriott Bengaluru Prestige Golfshire Resort & Spa": "/hotel-logos/property/jw-marriott-bengaluru-prestige-golfshire-resort-and-spa.png",
  "JW Marriott Goa": "/hotel-logos/property/jw-marriott-goa.png",
  "JW Marriott Hotel Bengaluru": "/hotel-logos/property/jw-marriott-hotel-bengaluru.png",
  "JW Marriott Hotel Chandigarh": "/hotel-logos/property/jw-marriott-hotel-chandigarh.png",
  "JW Marriott Hotel Kolkata": "/hotel-logos/property/jw-marriott-hotel-kolkata.png",
  "JW Marriott Hotel New Delhi Aerocity": "/hotel-logos/property/jw-marriott-hotel-new-delhi-aerocity.png",
  "JW Marriott Hotel Pune": "/hotel-logos/property/jw-marriott-hotel-pune.png",
  "JW Marriott Mumbai Juhu": "/hotel-logos/property/jw-marriott-mumbai-juhu.png",
  "JW Marriott Mumbai Sahar": "/hotel-logos/property/jw-marriott-mumbai-sahar.png",
  "JW Marriott Mussoorie Walnut Grove Resort & Spa": "/hotel-logos/property/jw-marriott-mussoorie-walnut-grove-resort-and-spa.png",
  "Jaipur Marriott Hotel": "/hotel-logos/property/jaipur-marriott-hotel.png",
  "Jaisalmer Marriott Resort & Spa": "/hotel-logos/property/jaisalmer-marriott-resort-and-spa.png",
  "Jim Corbett Marriott Resort & Spa": "/hotel-logos/property/jim-corbett-marriott-resort-and-spa.png",
  "Katra Marriott Resort & Spa": "/hotel-logos/property/katra-marriott-resort-and-spa.png",
  "Kochi Marriott Hotel": "/hotel-logos/property/kochi-marriott-hotel.png",
  "Lakeside Chalet, Mumbai - Marriott Executive Apartments": "/hotel-logos/property/lakeside-chalet-mumbai-marriott-executive-apartments.png",
  "Le Meridien Ahmedabad": "/hotel-logos/property/le-meridien-ahmedabad.png",
  "Le Meridien Amritsar": "/hotel-logos/property/le-meridien-amritsar.png",
  "Le Meridien Coimbatore": "/hotel-logos/property/le-meridien-coimbatore.png",
  "Le Meridien Dehradun Resort & Spa": "/hotel-logos/property/le-meridien-dehradun-resort-and-spa.png",
  "Le Meridien Goa, Calangute": "/hotel-logos/property/le-meridien-goa-calangute.png",
  "Le Meridien Gurgaon, Delhi NCR": "/hotel-logos/property/le-meridien-gurgaon-delhi-ncr.png",
  "Le Meridien Hyderabad": "/hotel-logos/property/le-meridien-hyderabad.png",
  "Le Meridien Jaipur Resort & Spa": "/hotel-logos/property/le-meridien-jaipur-resort-and-spa.png",
  "Le Meridien Kochi": "/hotel-logos/property/le-meridien-kochi.png",
  "Le Meridien Mahabaleshwar Resort & Spa": "/hotel-logos/property/le-meridien-mahabaleshwar-resort-and-spa.png",
  "Le Meridien Nagpur": "/hotel-logos/property/le-meridien-nagpur.png",
  "Le Meridien Navi Mumbai": "/hotel-logos/property/le-meridien-navi-mumbai.png",
  "Le Meridien New Delhi": "/hotel-logos/property/le-meridien-new-delhi.png",
  "Le Royal Meridien Chennai": "/hotel-logos/property/le-royal-meridien-chennai.png",
  "Marriott Executive Apartments Bengaluru UB City": "/hotel-logos/property/marriott-executive-apartments-bengaluru-ub-city.png",
  "Marriott Executive Apartments Hyderabad": "/hotel-logos/property/marriott-executive-apartments-hyderabad.png",
  "Marriott Executive Apartments Mall Road Amritsar": "/hotel-logos/property/marriott-executive-apartments-mall-road-amritsar.png",
  "Marriott Executive Apartments Navi Mumbai": "/hotel-logos/property/marriott-executive-apartments-navi-mumbai.png",
  "Marriott Suites Pune": "/hotel-logos/property/marriott-suites-pune.png",
  "Moxy Bengaluru Airport Prestige Tech Cloud": "/hotel-logos/property/moxy-bengaluru-airport-prestige-tech-cloud.png",
  "Moxy Mumbai Andheri West": "/hotel-logos/property/moxy-mumbai-andheri-west.png",
  "Mulberry Shades Bengaluru Nandi Hills, a Tribute Portfolio Resort": "/hotel-logos/property/mulberry-shades-bengaluru-nandi-hills-a-tribute-portfolio-resort.png",
  "Navi Mumbai Marriott Hotel": "/hotel-logos/property/navi-mumbai-marriott-hotel.png",
  "Port Muziris, a Tribute Portfolio Hotel, Kochi": "/hotel-logos/property/port-muziris-a-tribute-portfolio-hotel-kochi.png",
  "Renaissance Ahmedabad Hotel": "/hotel-logos/property/renaissance-ahmedabad-hotel.png",
  "Renaissance Bengaluru Race Course Hotel": "/hotel-logos/property/renaissance-bengaluru-race-course-hotel.png",
  "Renaissance Goa Hotel": "/hotel-logos/property/renaissance-goa-hotel.png",
  "Sheraton Grand Bangalore Hotel at Brigade Gateway": "/hotel-logos/property/sheraton-grand-bangalore-hotel-at-brigade-gateway.png",
  "Sheraton Grand Bengaluru Whitefield Hotel & Convention Center": "/hotel-logos/property/sheraton-grand-bengaluru-whitefield-hotel-and-convention-center.png",
  "Sheraton Grand Chennai Resort & Spa": "/hotel-logos/property/sheraton-grand-chennai-resort-and-spa.png",
  "Sheraton Grand Palace Indore": "/hotel-logos/property/sheraton-grand-palace-indore.png",
  "Sheraton Grand Pune Bund Garden Hotel": "/hotel-logos/property/sheraton-grand-pune-bund-garden-hotel.png",
  "Sheraton Hyderabad Hotel": "/hotel-logos/property/sheraton-hyderabad-hotel.png",
  "Sheraton New Delhi Hotel": "/hotel-logos/property/sheraton-new-delhi-hotel.png",
  "Surat Marriott Hotel": "/hotel-logos/property/surat-marriott-hotel.png",
  "THE ARTISTE KOCHI, A TRIBUTE PORTFOLIO HOTEL": "/hotel-logos/property/the-artiste-kochi-a-tribute-portfolio-hotel.png",
  "The Ritz-Carlton, Bangalore": "/hotel-logos/property/the-ritz-carlton-bangalore.png",
  "The Ritz-Carlton, Pune": "/hotel-logos/property/the-ritz-carlton-pune.png",
  "The St. Regis Goa Resort": "/hotel-logos/property/the-st-regis-goa-resort.png",
  "The St. Regis Mumbai": "/hotel-logos/property/the-st-regis-mumbai.png",
  "The Westin Chennai Velachery": "/hotel-logos/property/the-westin-chennai-velachery.png",
  "The Westin Goa": "/hotel-logos/property/the-westin-goa.png",
  "The Westin Gurgaon, New Delhi": "/hotel-logos/property/the-westin-gurgaon-new-delhi.png",
  "The Westin Hyderabad Hitec City": "/hotel-logos/property/the-westin-hyderabad-hitec-city.png",
  "The Westin Hyderabad Mindspace": "/hotel-logos/property/the-westin-hyderabad-mindspace.png",
  "The Westin Kolkata Rajarhat": "/hotel-logos/property/the-westin-kolkata-rajarhat.png",
  "The Westin Mumbai Garden City": "/hotel-logos/property/the-westin-mumbai-garden-city.png",
  "The Westin Mumbai Powai Lake": "/hotel-logos/property/the-westin-mumbai-powai-lake.png",
  "The Westin Pune Koregaon Park": "/hotel-logos/property/the-westin-pune-koregaon-park.png",
  "The Westin Pushkar Resort & Spa": "/hotel-logos/property/the-westin-pushkar-resort-and-spa.png",
  "Trinity Whitefield Bengaluru": "/hotel-logos/property/trinity-whitefield-bengaluru.png",
  "Udaipur Marriott Hotel": "/hotel-logos/property/udaipur-marriott-hotel.png",
  "W Goa": "/hotel-logos/property/w-goa.png",
};
